apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewer-svc-deployment
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: viewer-svc
    spec:
      containers:
        - image: 127.0.0.1:30400/viewer-svc
          imagePullPolicy: Always
          name: viewer-svc
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: viewer-svc-secrets
  selector:
    matchLabels:
      app: viewer-svc
